/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.DAO.UsuarioDAO;
import model.bean.Funcionarios;
import model.bean.Usuario;

/**
 *
 * @author Yuri
 */
public class NewJUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJUsuario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTusuario.getModel();
        jTusuario.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTusuario.getModel();
        modelo.setNumRows(0);
        UsuarioDAO pdao = new UsuarioDAO();
        
        for (Usuario h: pdao.read()) {
            modelo.addRow(new Object[]{
               h.getId(),
               h.getLogin(),
               h.getSenha(),
               h.getTipo_login(),
              
            });
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JButton Cadastrar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        txtTipo_login = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTusuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 51, 179, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SENHA :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 90, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("TIPO  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 124, 50, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("INSERINDO NOVOS USUÁRIOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 90, 178, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("LOGIN :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 54, -1, -1));

        Cadastrar.setBackground(new java.awt.Color(0, 153, 51));
        Cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        Cadastrar.setText("CADASTRAR");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 100, -1));

        Excluir.setBackground(new java.awt.Color(255, 102, 102));
        Excluir.setForeground(new java.awt.Color(255, 255, 255));
        Excluir.setText("EXCLUIR");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 100, -1));

        Atualizar.setBackground(new java.awt.Color(255, 255, 153));
        Atualizar.setText("ATUALIZAR");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 100, -1));

        Voltar.setText("↩");
        Voltar.setToolTipText("");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        txtTipo_login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTipo_login.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "usuario", "supervisor" }));
        jPanel1.add(txtTipo_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 120, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/usuarios.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 210, 200));

        jTusuario.setForeground(new java.awt.Color(0, 51, 153));
        jTusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "login", "senha", "tipo_login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTusuarioMouseClicked(evt);
            }
        });
        jTusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTusuarioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTusuario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // cadastrando
        Usuario h = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();

        h.setLogin(txtLogin.getText());
        h.setSenha(txtSenha.getText());
        h.setTipo_login(txtTipo_login.getSelectedItem().toString());
        
        dao.create(h);
        txtLogin.setText("");
        txtSenha.setText("");
        
        readJTable();
        
        
        
        
        
        
    }//GEN-LAST:event_CadastrarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void jTusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTusuarioKeyReleased
        // TODO add your handling code here:
        if (jTusuario.getSelectedRow()!= -1 )  {
            txtLogin.setText(jTusuario.getValueAt(jTusuario.getSelectedRow(), 1).toString());
            
            txtSenha.setText(jTusuario.getValueAt(jTusuario.getSelectedRow(), 2).toString());
            txtTipo_login.setSelectedItem(jTusuario.getValueAt(jTusuario.getSelectedRow(), 3).toString());
            
        }
        
        
        
    }//GEN-LAST:event_jTusuarioKeyReleased

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        if (jTusuario.getSelectedRow()!= -1 ){
            
            Usuario h = new Usuario();
            UsuarioDAO dao = new UsuarioDAO();

            
            h.setId((int)jTusuario.getValueAt(jTusuario.getSelectedRow(), 0));
            
            dao.delete(h);
            txtLogin.setText("");
            
            txtSenha.setText("");
            
            readJTable();           

        
        } else{
        
                JOptionPane.showMessageDialog(null,"Selecione um item para excluir.");
        
        }
        
        
    }//GEN-LAST:event_ExcluirActionPerformed

    private void jTusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTusuarioMouseClicked
        // TODO add your handling code here:
        
        if (jTusuario.getSelectedRow()!= -1 )  {
            txtLogin.setText(jTusuario.getValueAt(jTusuario.getSelectedRow(), 1).toString());
            
            txtSenha.setText(jTusuario.getValueAt(jTusuario.getSelectedRow(), 2).toString());
            txtTipo_login.setSelectedItem(jTusuario.getValueAt(jTusuario.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_jTusuarioMouseClicked

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        // TODO add your handling code here:
        if (jTusuario.getSelectedRow()!= -1 ){
            
            Usuario h = new Usuario();
            UsuarioDAO dao = new UsuarioDAO();

            h.setLogin(txtLogin.getText());
            h.setSenha(txtSenha.getText());
            h.setTipo_login(txtTipo_login.getSelectedItem().toString());
            
            h.setId((int)jTusuario.getValueAt(jTusuario.getSelectedRow(), 0));
            
            dao.update(h);
            txtLogin.setText("");    
            txtSenha.setText("");            
            readJTable();
        
        }
    }//GEN-LAST:event_AtualizarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        new ViewMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTusuario;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JComboBox<String> txtTipo_login;
    // End of variables declaration//GEN-END:variables
}
