/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.DAO.FornecedorDAO;
import model.bean.Fornecedor;


/**
 *
 * @author Yuri
 */
public class ViewFornecedorSupervisor extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ViewFornecedorSupervisor() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTfornecedores.getModel();
        jTfornecedores.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTfornecedores.getModel();
        modelo.setNumRows(0);
        FornecedorDAO pdao = new FornecedorDAO();
        
        for (Fornecedor d: pdao.read()) {
            modelo.addRow(new Object[]{
               d.getId(),
               d.getNome_fornecedor(),
               d.getCnpj_fornecedor(),
               d.getTipo_fornecimento(),
               
            });
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNome_fornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTipo_fornecimento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCnpj_fornecedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTfornecedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome_fornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome_fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 51, 179, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CNPJ :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIPO :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 30));
        jPanel1.add(txtTipo_fornecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 124, 180, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Olá supervisor(a)! Veja abaixo nossos fornecedores!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        txtCnpj_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpj_fornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtCnpj_fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 90, 178, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOME :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 54, -1, -1));

        Voltar.setText("↩");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Energia-Solar-Será-Usada-Na-Transposição-do-São-Francisco-_-capa-blog-752x440.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 180));

        jTfornecedores.setForeground(new java.awt.Color(0, 51, 153));
        jTfornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CNPJ", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTfornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTfornecedoresMouseClicked(evt);
            }
        });
        jTfornecedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTfornecedoresKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTfornecedores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCnpj_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpj_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpj_fornecedorActionPerformed

    private void txtNome_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome_fornecedorActionPerformed

    private void jTfornecedoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfornecedoresKeyReleased
        // TODO add your handling code here:
        if (jTfornecedores.getSelectedRow()!= -1 )  {
            txtNome_fornecedor.setText(jTfornecedores.getValueAt(jTfornecedores.getSelectedRow(), 1).toString());
            txtTipo_fornecimento.setText(jTfornecedores.getValueAt(jTfornecedores.getSelectedRow(), 2).toString());
            txtCnpj_fornecedor.setText(jTfornecedores.getValueAt(jTfornecedores.getSelectedRow(), 3).toString());
            
        }
        
        
        
    }//GEN-LAST:event_jTfornecedoresKeyReleased

    private void jTfornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTfornecedoresMouseClicked
        // TODO add your handling code here:
        
        if (jTfornecedores.getSelectedRow()!= -1 )  {
            txtNome_fornecedor.setText(jTfornecedores.getValueAt(jTfornecedores.getSelectedRow(), 1).toString());
            txtTipo_fornecimento.setText(jTfornecedores.getValueAt(jTfornecedores.getSelectedRow(), 2).toString());
            txtCnpj_fornecedor.setText(jTfornecedores.getValueAt(jTfornecedores.getSelectedRow(), 3).toString());
            
        }
    }//GEN-LAST:event_jTfornecedoresMouseClicked

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        new ViewMenuSupervisor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedorSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedorSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedorSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFornecedorSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFornecedorSupervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTfornecedores;
    private javax.swing.JTextField txtCnpj_fornecedor;
    private javax.swing.JTextField txtNome_fornecedor;
    private javax.swing.JTextField txtTipo_fornecimento;
    // End of variables declaration//GEN-END:variables
}
